name: OFRP CI
on:
  workflow_dispatch:
jobs:
  build:
    name: OFRP Build CI
    runs-on: ubuntu-20.04
    env:
      OEM: samsung
      DEVICE: jflte
      BRANCH: twrp-6.0
    steps:
      - uses: actions/checkout@v2
      - name: Installing build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses5 python axel
      - name: Install OpenJDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Syncing OFRP sources
        run: |
          mkdir ~/OFRP
          cd ~/OFRP
          mkdir ~/.bin
          curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          python3 ~/.bin/repo init --depth=1 -u https://github.com/unlegacy-devices/fox-7.1_manifest.git -b twrp-7.1
          python3 ~/.bin/repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
          git clone --depth=1 --branch android-7.1.2_r38 --single-branch https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8 /opt/toolchains/arm-eabi-4.8
          git clone --depth=1 --branch android-7.1 --single-branch https://github.com/unlegacy-devices/android_device_samsung_s3ve3g.git device/samsung/s3ve3g
          git clone --depth=1 --branch lineage-14.1 --single-branch https://github.com/NotNoelChannel/android_kernel_samsung_s3ve3g/ kernel/samsung/s3ve3g
      - name: Building OFRP
        run: |
          cd ~/OFRP
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export LC_ALL="C"
          export OF_MAINTAINER="NotNoelChannel"
          export OF_DISABLE_MIUI_SPECIFIC_FEATURES=1
          export OF_LEGACY_SHAR512=1
          export FOX_USE_LZMA_COMPRESSION=1
          export FOX_REMOVE_AAPT=1
          export OF_DISABLE_KEYMASTER2=1
          lunch omni_s3ve3g-eng
          make -j$(nproc --all) recoveryimage
      - name: Uploading OFRP builds
        uses: actions/upload-artifact@v2
        with:
          name: ofrp
          path: /home/runner/OFRP/out/target/product/s3ve3g/recovery.*
